### ISSUE TITLE
Wrong parameter for process.kill

### ISSUE THREAD

**Issue by ghost** [tkellen/js-flagged-respawn#5]
https://github.com/js-cli/js-flagged-respawn/blob/master/test/bin/signal.js#L13

`process.kill` takes a signal in numeric format not string format.
Meaning it needs to be `1` instead of `SIGHUP`.

**Comment by tkellen** [comment]
Thanks for the heads up--would you mind submitting a PR to resolve this?

**Comment by ghost** [comment]
Apparently `child_process` takes `String` and `process` takes `Number`.
So it will not be a bug.
